[package]
name = "rluadecomp"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
env_logger = "0.11.7"
log = "0.4.27"
nom = "8.0.0"
num_enum = "0.7.3"
